### ISSUE TITLE
pre-release features roadmap

### ISSUE THREAD

**Issue by Fluffyalien1422** [Fluffyalien1422/bedrock-energistics#1]
The following tasks are subject to change.

# ~~v0.4~~
- [x] solar panel
- [x] crusher
- [x] oil extractor
- [x] oil generator
- [x] atmospheric condenser
- [x] centrifuge
- [x] coal generator
- [x] organic generator
- [x] powered furnace
- [x] add light emission to some machines when active

# ~~v0.6~~
- [x] new textures
- [x] block breaker
- [x] block placer

# ~~v0.8~~
- [x] make generators have the storage bar that they generate on the right, while consumers have it on the left
- [x] void miner
- [x] fluid separator - separates oil into hydrogen and carbon (2.25x more hydrogen than carbon)
- [x] ammonia factory - converts nitrogen & hydrogen into ammonia
- [x] ammonia generator - generates power from ammonia

# ~~v0.9~~
- [x] disposal unit - disposes of unwanted fluids or gases. can be configured to accept only a specific storage type
- [x] battery
- [x] fluid tank
- [x] gas canister
- [x] pump
- [x] make fluid separator separate water into oxygen and hydrogen

# ~~v0.10~~
- [x] tesseract
- [x] item charger (for asn wireless interface and possible future bedrock energistics item machines)

# ~~v0.11~~
- [x] interact with fluid tank with bucket to get a bucket of that fluid (only water and lava)

# ~~v0.12~~
- [x] basic refinery - converts items, gases, and liquids into different materials (eg. carbon = coal) (multiple items, gases, and liquids may be required for one recipe)
- [x] network monitor
- [x] lava generator - generates power from lava
- [x] water generator - generates power from water
- [x] crucible - converts cobblestone to lava

# v0.13
- [ ] add refined materials created in the basic refinery which can be used for crafting recipes (ammonia fabricator and generator will require advanced machine parts which will require refined materials)
- [ ] advanced refinery - can create diamonds from hydrogen and carbon

# v1.0
- [ ] powered passive spawner - spawns passive mobs
- [ ] powered monster spawner - spawns monsters
- [ ] powered nether spawner - spawns nether monsters
